"""Generate goldens for OCamlCalc with Decimal ROUND_HALF_EVEN.
Same spec as engine/excore.ml: loan = annuity (exact-rational payment via
big-int powers, monthly interest = he(balance_cents * pct / 1200)), last month
absorbs residual; savings = deposit then he(bal*pct/1200) monthly;
compound = discrete he steps + exact AER at 1e-12 pct.

Outputs tests/goldens.json (node suite) AND tests/goldens.ml
(native dune suite) so both runtimes are pinned to the same vectors.
"""
from decimal import Decimal, ROUND_HALF_EVEN, getcontext
import json

getcontext().prec = 80

def he(x: Decimal) -> int:
    return int(x.quantize(Decimal(1), rounding=ROUND_HALF_EVEN))

def parse2(s):
    return he(Decimal(s) * 100)

def loan(amount_s, pct_s, months):
    P = parse2(amount_s)
    pct = Decimal(pct_s)
    if pct == 0:
        pay = he(Decimal(P) / Decimal(months))
    else:
        b = Decimal(1200)
        a = 1 + pct / 1200
        # exact rational: payment = P*pct*a^n*100^? — do it scaled:
        # payment_cents = he( P * pct/1200 / (1-a^-n) ) with P in cents,
        # computed as ratio of integers to stay exact under prec=80.
        n = months
        an_num0, an_den0 = a.as_integer_ratio()
        an_num, an_den = an_num0 ** n, an_den0 ** n
        # 1 - a^-n = (a^n - 1)/a^n
        num = Decimal(P) * pct * an_num
        den = Decimal(1200) * (an_num - an_den)
        pay = he(num / den)
    bal = P
    ti = 0
    sched = []
    for m in range(1, months + 1):
        interest = he(Decimal(bal) * pct / Decimal(1200))
        if m == months:
            principal = bal
            bal = 0
        else:
            principal = pay - interest
            bal -= principal
        ti += interest
        sched.append({"m": m, "i": str(interest), "p": str(principal), "b": str(bal)})
    return {"payment": str(pay), "totalInterest": str(ti),
            "totalPaid": str(P + ti), "schedule": sched}

def savings(init_s, dep_s, pct_s, years):
    bal = parse2(init_s)
    dep = parse2(dep_s)
    pct = Decimal(pct_s)
    deposited = bal
    ti = 0
    for _ in range(years * 12):
        bal += dep
        deposited += dep
        i = he(Decimal(bal) * pct / Decimal(1200))
        bal += i
        ti += i
    return {"finalBalance": str(bal), "totalDeposited": str(deposited),
            "totalInterest": str(ti)}

def compound(principal_s, pct_s, years, per_year):
    v = parse2(principal_s)
    pct = Decimal(pct_s)
    D = Decimal(100 * per_year)
    for _ in range(per_year * years):
        v = he(Decimal(v) * (D + pct) / D)
    growth = (Decimal(1) + pct / D) ** per_year
    aer_pct = (growth - 1) * 100
    return {"finalValue": str(v), "effectiveAnnualPct12": str(
        aer_pct.quantize(Decimal("0.000000000001"), rounding=ROUND_HALF_EVEN))}

cases = {
    "loan_basic_100k_12pc_24m": loan("100000", "12", 24),
    "loan_zero_rate": loan("50000", "0", 12),
    "loan_odd_months": loan("12345.67", "13.37", 37),
    "loan_half_even_probe": loan("100", "2.5", 3),
    "loan_big_950m": loan("950000000", "7.77", 360),
    "savings_basic": savings("1000", "200", "10", 5),
    "savings_no_init": savings("0", "50", "6.25", 3),
    "compound_quarterly": compound("25000", "8.5", 10, 4),
    "compound_daily": compound("10000", "5.25", 7, 365),
}

# engine success payloads are uniform: {"ok":true, ...} — bake into goldens
for v in cases.values():
    v_ok = {"ok": True}
    v_ok.update(v)
    v.clear()
    v.update(v_ok)

goldens = json.dumps(cases, indent=1)

ml = ["(* GENERATED by scripts/gen_goldens.py — do not edit by hand. *)",
      "let goldens : (string * string) list = ["]
for k, v in cases.items():
    s = json.dumps(v, separators=(",", ":")).replace("\\", "\\\\").replace('"', '\\"')
    ml.append(f'  ("{k}", "{s}");')
ml.append("]")

with open("tests/goldens.json", "w", newline="\n") as f:
    f.write(goldens + "\n")
with open("tests/goldens.ml", "w", newline="\n") as f:
    f.write("\n".join(ml) + "\n")
print("wrote tests/goldens.json and tests/goldens.ml")
